import mongoose, {Schema} from 'mongoose';
const rootSchema = new Schema(
    {
        root_id: String, 
        benjan: String,
        letter1: String,
        letter2: String,
        letter3: String,
        letter4: String,
        descript: String,
        sound: String,
        inf: String,
        infS: String,
        p1s: String,
        p1sS: String,
        p2sm: String,
        p2smS: String,
        p2sw: String,
        p2swS: String,
        p3sm: String,
        p3smS: String,
        p3sw: String,
        p3swS: String,
        p1m: String,
        p1mS: String,
        p2mm: String,
        p2mmS: String,
        p2mw: String,
        p2mwS: String,
        p3m: String,
        p3mS: String,
        nsm: String,
        nsmS: String,
        nsw: String,
        nswS: String,
        nmm: String,
        nmmS: String,
        nmw: String,
        nmwS: String,
        f1s: String,
        f1sS: String,
        f2sm: String,
        f2smS: String,
        f2sw: String,
        f2swS: String,
        f3sm: String,
        f3smS: String,
        f3sw: String,
        f3swS: String,
        f1m: String,
        f1mS: String,
        f2mm: String,
        f2mmS: String,
        f2mw: String,
        f2mwS: String,
        f3m: String,
        f3mS: String,
        ism: String,
        ismS: String,
        isw: String,
        iswS: String,
        imm: String,
        immS: String,
        imw: String,
        imwS: String,
        ns: String,
        nsS: String,
        nm: String,
        nmS: String,
        asm: String,
        asmS: String,
        asw: String,
        aswS: String,
        amm: String,
        ammS: String,
        amw: String,
        amwS: String
    },
    {
        timestamps: true
    }
);
const ObjectId = Schema.ObjectId;
const root = mongoose.model('root', rootSchema );

export default root;